### PR TITLE
Http provider support multi

### LINKED ISSUE #2949: No subscribeStorage when provider doesn't support subscription
Currently when httpProvider is used, 
1. `api.query.<module>.<storage>` don't have `.multi()`
2. `api.queryMulti()` will fail
3. all derive queries that depend on multi() or queryMulti will fail.

The reason mentioned in the code comment says `rpc.getStorage` doesn't support multi keys while `rpc.subscribeStorage` supports. But it was out of date because `rpc.queryStorageAt` can be used as the equvalence of `rpc.subscribeStorage`  for httpProvider.

### PR DESCRIPTION
**Pull request by ianhe8x**
Fixes #2949

I found e2e tests are removed from the repo, but to demonstrate how my changes works I committed some simple tests and will remove them once my PR get approved.

### CODE REVIEW

**Comment by ianhe8x** [comment]
Move my tests from PR to here.
```
function createHttpApi (): Promise<ApiPromise> {
  jest.setTimeout(30000);
  process.env.NODE_ENV = 'test';

  const provider = new HttpProvider('https://kusama.api.onfinality.io/public');
  // const provider = new WsProvider('wss://westend-rpc.polkadot.io/');
  // const provider = new WsProvider('ws://127.0.0.1:9944/');

  return new ApiPromise({ provider }).isReady;
}

describe('test multi query', function () {
  it('api.query.system.account.multi()', async (): Promise<void> => {
    const api = await createApi();
    const b1 = await api.query.system.account('HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP');
    const b2 = await api.query.system.account('DSLxCoJ4VyjYvpqoEHciLFQdFzdXPyXpMw85QpgE3mVSz2Z');
    const [mb1, mb2] = await api.query.system.account.multi(['HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP', 'DSLxCoJ4VyjYvpqoEHciLFQdFzdXPyXpMw85QpgE3mVSz2Z']);
    expect(b1.eq(mb1)).toBeTruthy();
    expect(b2.eq(mb2)).toBeTruthy();
  });
  it('api.queryMulti()', async (): Promise<void> => {
    const api = await createApi();
    const b1 = await api.query.system.account('HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP');
    const i1 = await api.query.identity.identityOf('HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP');
    const [mb1, mi1] = await api.queryMulti([
      [api.query.system.account, 'HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP'],
      [api.query.identity.identityOf, 'HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP'],
    ])
    expect(b1.eq(mb1)).toBeTruthy();
    expect(i1.eq(mi1)).toBeTruthy();
  });

  it('api.query.system.account.multi() over HttpProvider', async (): Promise<void> => {
    const api = await createHttpApi();
    const b1 = await api.query.system.account('HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP');
    const b2 = await api.query.system.account('DSLxCoJ4VyjYvpqoEHciLFQdFzdXPyXpMw85QpgE3mVSz2Z');
    const [mb1, mb2] = await api.query.system.account.multi(['HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP', 'DSLxCoJ4VyjYvpqoEHciLFQdFzdXPyXpMw85QpgE3mVSz2Z']);
    expect(b1.eq(mb1)).toBeTruthy();
    expect(b2.eq(mb2)).toBeTruthy();
  });
  it('api.queryMulti() over HttpProvider', async (): Promise<void> => {
    const api = await createHttpApi();
    const b1 = await api.query.system.account('HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP');
    const i1 = await api.query.identity.identityOf('HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP');
    const [mb1, mi1] = await api.queryMulti([
      [api.query.system.account, 'HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP'],
      [api.query.identity.identityOf, 'HRuaGanNmkmeQgZPWPXmkZJb944raNS5ni2vhKzhz75zVYP'],
    ])
    expect(b1.eq(mb1)).toBeTruthy();
    expect(i1.eq(mi1)).toBeTruthy();
  });

  it('derive query over WsProvider', async (): Promise<void> => {
    const api = await createApi();
    const validators = await api.derive.staking.validators();
    expect(validators).toBeTruthy();
    const accounts = await api.derive.staking.accounts(validators.validators);
    expect(accounts).toBeTruthy();
    expect(accounts.length).toBeTruthy();
  })

  it('derive query over HttpProvider', async (): Promise<void> => {
    const api = await createHttpApi();
    const validators = await api.derive.staking.validators();
    expect(validators).toBeTruthy();
    const accounts = await api.derive.staking.accounts(validators.validators);
    expect(accounts).toBeTruthy();
    expect(accounts.length).toBeTruthy();
  })
});
```

**Comment by jacogr** [comment]
Ok, now I see the PR, after I commented :) Ok, will go through - if innocent enough can support it, at first glance it _seems_ innocent enough.

(The e2e tests were removed since they had/have severe rot with the pace at which endpoints and responses move around)

File: packages/api/src/base/Decorate.ts [hunk 1]
```diff
@@ -454,7 +453,10 @@ export abstract class Decorate<ApiType extends ApiTypes> extends Events {
       ...Array(Math.ceil(keys.length / PAGE_SIZE_VALS))
         .fill(0)
         .map((_, index): Observable<Codec[]> =>
-          this._rpcCore.state.subscribeStorage(keys.slice(index * PAGE_SIZE_VALS, (index * PAGE_SIZE_VALS) + PAGE_SIZE_VALS))
+          ((this.hasSubscriptions || !this._rpcCore.state.queryStorageAt)
```
Comment (jacogr) [inline packages/api/src/base/Decorate.ts:456]: There is a slight issue here - if the provider connects to a chain without subscriptions and no queryStorageAt, it will still try to use the subscription. (This is unlike the original where this was just not available)

The `_decorateMulti ` above has the same issue.

Comment (ianhe8x) [reply packages/api/src/base/Decorate.ts:465]: Now the decoration will be skipped if `this.supportMulti` is false.

Comment (jacogr) [reply packages/api/src/base/Decorate.ts:466]: Thank you, will take  proper look in the next short while - looks promising from a cursory glance.

File: packages/api/src/base/Decorate.ts [hunk 2]
```diff
@@ -454,7 +463,10 @@ export abstract class Decorate<ApiType extends ApiTypes> extends Events {
...
```
Comment (jacogr) [inline packages/api/src/base/Decorate.ts:466]:
```suggestion
          (this.hasSubscriptions
```

Just one small change to align with `_decorateMulti` above

**Review by jacogr — COMMENTED** [review]
Great, thank you. I only have one small comment, the rest looks sane (and fixes the HTTP decorated-but-not-working bug as well)

File: packages/api/src/base/Decorate.ts (hunk 2 above)
Comment (ianhe8x) [reply packages/api/src/base/Decorate.ts]: updated

**Review by jacogr — APPROVED** [review]
Brilliant, thank you!

I hope this addresses your usecase fully.
