### PR TITLE
Initial DoubleMap support (support v3 Metadata)

### LINKED ISSUE #799: Metadata load failure should exit early
Currently it seems like the “unknown Metadata version” is swallowed and then use of the API spits out wrong errors. 

I believe it it the fallback to v0 that just parses garbage. Can remove v0 parsing support as a start.

### PR DESCRIPTION
**Pull request by jacogr**
- Part of https://github.com/polkadot-js/api/issues/776
- Closes #799

### CODE REVIEW

**Comment by jacogr** [comment]
Yes, I was expecting use, however the only thing that changed running the PR was the version

File: packages/types/src/Metadata/v3/toV2.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+// Copyright 2017-2019 @polkadot/types authors & contributors
+// This software may be modified and distributed under the terms
+// of the Apache-2.0 license. See the LICENSE file for details.
+
+import MetadataV2 from '../v2/Metadata';
+import MetadataV3 from '.';
+
+export default function toV2 (v2: MetadataV3): MetadataV2 {
+  return new MetadataV2(v2);
```
Comment (xlc) [inline packages/types/src/Metadata/v3/toV2.ts]: `DoubleMapType` only exists in v3 so this should fail if trying to convert a metadata includes double to v2.
One way to solve this (without refactor everything to make upgrade instead of downgrade), is duplicate `DoubleMapType` in v2 like how I retrofit `is_linked` in v1
