### PR TITLE
fix: check if minimumPeriod is zero

### LINKED ISSUE #5826: Support `minimumPeriod` of `0`
With the switch to async backing, parachains will set a `minimumPeriod` of `0`. (Not all, but some).

This currently breaks transaction signing here: https://github.com/polkadot-js/api/blob/8dbc373ac573e8c7aea580e8d17d634e40f01956/packages/api-derive/src/tx/signingInfo.ts#L88

We should check that if `minimumPeriod` is `0` and then just also use the fallback duration. On top of that we should use `SlotDuration` from Aura: https://github.com/paritytech/polkadot-sdk/pull/3732 as we use `ExpectedBlockTime` from Babe.

### PR DESCRIPTION
**Pull request by pepoviola**
Fix #5826 

Add check to ensure we don't use `0`.

### CODE REVIEW

File: packages/api-derive/src/tx/signingInfo.ts [hunk 1]
```diff
@@ -84,8 +84,8 @@ export function signingInfo (_instanceId: string, api: DeriveApi): (address: str
           api.consts.system?.blockHashCount?.toNumber() || FALLBACK_MAX_HASH_COUNT,
           MORTAL_PERIOD
             .div(
-              api.consts.babe?.expectedBlockTime ||
-              api.consts.timestamp?.minimumPeriod.muln(2) ||
+              (!api.consts.babe?.expectedBlockTime.isZero() && api.consts.babe?.expectedBlockTime) ||
+              (!api.consts.aura?.slotDuration.isZero() && api.consts.aura.slotDuration) ||
```
Comment (pepoviola) [inline packages/api-derive/src/tx/signingInfo.ts:88]: Maybe is better to use a helper function to check that is not `zero` for both (babe/aura) fields.

Comment (TarikGul) [reply packages/api-derive/src/tx/signingInfo.ts]: Yea this makes sense! WIll help clean it up a bit

**Comment by TarikGul** [comment]
Since the augmented types dont have the aura consts yet, you will have to type case a custom type on `api.consts.aura` that sets slotDuration as a key value to `AugmentedConsts<"rxjs">.aura`. This can be all done locally inside of the api-derive.

**Comment by pepoviola** [comment]
> Since the augmented types dont have the aura consts yet, you will have to type case a custom type on `api.consts.aura` that sets slotDuration as a key value to `AugmentedConsts<"rxjs">.aura`. This can be all done locally inside of the api-derive.

Oks, does make sense to use the old version

```ts
(!api.consts.timestamp?.minimumPeriod.isZero() && api.consts.timestamp.minimumPeriod.muln(2) ) ||
```

until https://github.com/paritytech/polkadot-sdk/pull/3732 is merged so we can use the aura const?

**Comment by TarikGul** [comment]
> > Since the augmented types dont have the aura consts yet, you will have to type case a custom type on `api.consts.aura` that sets slotDuration as a key value to `AugmentedConsts<"rxjs">.aura`. This can be all done locally inside of the api-derive.
> 
> Oks, does make sense to use the old version
> 
> ```ts
> (!api.consts.timestamp?.minimumPeriod.isZero() && api.consts.timestamp.minimumPeriod.muln(2) ) ||
> ```
> 
> until [paritytech/polkadot-sdk#3732](https://github.com/paritytech/polkadot-sdk/pull/3732) is merged so we can use the aura const?

If we can maintain the same logic and patch with this then sure that is totally acceptable!

File: packages/api-derive/src/tx/signingInfo.ts [hunk 2]
```diff
@@ -12,6 +12,9 @@ import { isNumber, isUndefined } from '@polkadot/util';
 
 import { unwrapBlockNumber } from '../util/index.js';
 import { FALLBACK_MAX_HASH_COUNT, FALLBACK_PERIOD, MAX_FINALITY_LAG, MORTAL_PERIOD } from './constants.js';
+import { AugmentedConsts } from '@polkadot/api-base/types';
```
Comment (TarikGul) [inline packages/api-derive/src/tx/signingInfo.ts:15]:
```suggestion
import type { AugmentedConsts } from '@polkadot/api-base/types';
```

File: packages/api-derive/src/tx/signingInfo.ts [hunk 3]
```diff
@@ -63,6 +66,20 @@ function signingHeader (api: DeriveApi): Observable<Header> {
   );
 }
 
+interface Aura {
+  slotDuration: u64 & AugmentedConsts<'rxjs'>;
+}
+
+function babeOrAuraPeriod(api: DeriveApi) : AnyNumber|undefined {
```
Comment (TarikGul) [inline packages/api-derive/src/tx/signingInfo.ts:73]:
```suggestion
function babeOrAuraPeriod(api: DeriveApi) : BN | undefined {
```

This will also require the following

```typescript
import type { BN } from '@polkadot/util';
```

**Review by TarikGul — CHANGES_REQUESTED** [review]
Few nits, but looks amazing. Once the suggestions are fixed this should be good to go. Also needs a `yarn lint` once the following is fixed.

**Comment by pepoviola** [comment]
> Few nits, but looks amazing. Once the suggestions are fixed this should be good to go. Also needs a `yarn lint` once the following is fixed.

Thanks for review it, I made those changes 👍

**Review by TarikGul — APPROVED** [review]
LGTM 🚀

File: packages/api-derive/src/tx/signingInfo.ts [hunk 4]
```diff
@@ -63,6 +66,19 @@ function signingHeader (api: DeriveApi): Observable<Header> {
...
 
+interface Aura {
+  slotDuration: u64 & AugmentedConsts<'rxjs'>;
+}
+
+function babeOrAuraPeriod (api: DeriveApi): BN | undefined {
+  const period = api.consts.babe?.expectedBlockTime ||
+    // this will be present ones https://github.com/paritytech/polkadot-sdk/pull/3732 is merged
+    (api.consts['aura'] as unknown as Aura)?.slotDuration ||
+    api.consts.timestamp?.minimumPeriod;
```
Comment (sinzii) [inline packages/api-derive/src/tx/signingInfo.ts:77]: Hi everyone, I notice that we do `x2` (`.muln(2)`) for the `minimumPeriod` previously, but now we removed it here. I didn't see we mentioned this change anywhere, any reason for this? I just want to confirm that this is intentional. Thank you!

Comment (pepoviola) [reply packages/api-derive/src/tx/signingInfo.ts:77]: Hey @sinzii, thanks for the heads up! This was an error, this [pr](https://github.com/polkadot-js/api/pull/5829) fix it.
Thx!

Comment (sinzii) [reply packages/api-derive/src/tx/signingInfo.ts:77]: Awesome, thanks for the quick fix!
