### PR TITLE
fix: Fixes #154 Modify TypeDocs that change the source to resolve rendering correctly

### LINKED ISSUE #154: API documentation does not render correctly
https://github.com/polkadot-js/api/blob/master/docs/api/classes/_index_.api.md

Seems like there is a missing "```" somewhere. Example doesn't render as example, text renders as, well, text.

And a link to the gitbook pages - https://polkadot.js.org/api/api/classes/_index_.api.html and this (looks) a bit worse https://polkadot.js.org/api/api-provider/classes/_ws_index_.wsprovider.html

### PR DESCRIPTION
**Pull request by ltfschoen**
* Add TypeDoc/TSDoc labels

* Use HTML <BR> element in TypeDoc to generate new lines even to achieve a newline between lines of code

* Use HTML `<PRE><CODE>` combination in TypeDoc for multiple line code generation

* Add missing TypeDocs for HTTP `constructor` and `send` for HTTP and WS

* Remove unnecessary assignment of `= true` default value in TypeDoc @param value and clean up text alignment

* Verified that it displays correctly in development environment by running `yarn; yarn polkadot-dev-build-docs; yarn gitbook serve`, and then navigating to localhost:4000

### CODE REVIEW

File: packages/api/src/index.ts [hunk 1]
```diff
@@ -46,14 +51,17 @@ export default class Api implements ApiInterface {
 
   /**
    * @name signature
-   * @signature jsonrpcSignature (method: InterfaceMethodDefinition): string
+   * @signature `jsonrpcSignature (method: InterfaceMethodDefinition): string`
```
Comment (jacogr) [inline packages/api/src/index.ts]: This could be whacked. I actually saw it a day or two ago and then got ditracted. (It was for my lil jsdoc extension that built the docs on flowtype - when it still worked)

Comment (ltfschoen) [reply packages/api/src/index.ts]: I've pushed commit c9bc957 that removes this line
