### PR TITLE
Make the 2nd argument to SubmittableExtrinsic.sign/signAsync optional

### LINKED ISSUE #2012: Make options for `.signAsync` optional
### Goal:

Update `signAsync` to make the second argument optional, and default to `{}`

### Background:

Currently this code will crash:

`const signed = await api.system.remark().signAsync(pair, options);` when `options` is `undefined`, it gives this error

```
(node:78914) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'nonce' of undefined
    at Submittable.value (/Users/xiliangchen/projects/playground/node_modules/@polkadot/api/submittable/createClass.js:59:42)
    at Submittable.value (/Users/xiliangchen/projects/playground/node_modules/@polkadot/api/submittable/createClass.js:129:99)
    at /Users/xiliangchen/projects/playground/node_modules/@polkadot/api/submittable/createClass.js:251:110
    at /Users/xiliangchen/projects/playground/node_modules/@polkadot/api/promise/Api.js:78:14
    at Submittable.signAsync (/Users/xiliangchen/projects/playground/node_modules/@polkadot/api/submittable/createClass.js:251:170)
    at /Users/xiliangchen/projects/playground/index.ts:28:33
    at step (/Users/xiliangchen/projects/playground/index.ts:33:23)
    at Object.next (/Users/xiliangchen/projects/playground/index.ts:14:53)
    at /Users/xiliangchen/projects/playground/index.ts:8:71
    at new Promise (<anonymous>)
```

### Actions:

Make second argument optional

https://github.com/polkadot-js/api/blob/e77050b9f59a0b772d1d0b8c5c1da488a7c36810/packages/api/src/submittable/createClass.ts#L72

Update interface

https://github.com/polkadot-js/api/blob/e77050b9f59a0b772d1d0b8c5c1da488a7c36810/packages/api/src/submittable/types.ts#L55

Provide appropriate unit tests.

----

@jacogr please tag this if you are happy about this.

Tags:
`bounty-awaiting-approval`
`bounty-XS`

### PR DESCRIPTION
**Pull request by KiChjang**
Fixes #2012.

### CODE REVIEW

**Comment by developerfred** [comment]
Nice job @KiChjang!

File: packages/api/src/submittable/createClass.ts [hunk 1]
```diff
@@ -224,7 +224,9 @@ export default function createClass <ApiType extends ApiTypes> ({ api, apiType,
 
     // NOTE here we actually override nonce if it was specified (backwards compat for
     // the previous signature - don't let userspace break, but allow then time to upgrade)
-    #optionsOrNonce = (optionsOrNonce: Partial<SignerOptions>): Partial<SignerOptions> => {
+    #optionsOrNonce = (optionsOrNonce?: Partial<SignerOptions>): Partial<SignerOptions> => {
+      if (!optionsOrNonce) return {};
+
```
Comment (jacogr) [inline packages/api/src/submittable/createClass.ts:229]:
```suggestion
    #optionsOrNonce = (optionsOrNonce: Partial<SignerOptions> = {}): Partial<SignerOptions> => {
```
