### PR TITLE
Fix raw payload

### LINKED ISSUE #1364: inconsistent between toPayload() and toRaw()
I've got Invalid Transaction (0) error when upgrading sdk, after hours debuging it turn out because of the signer I used in my test is a rawSigner.
RawSigner should be able to do the job same as PayloadSigner, but I found they are feed with different data.
I've work out a fix for this.

### PR DESCRIPTION
**Pull request by ianhe8x**
Fix #1364 
base on my PR #1360 

the only place changed is in `SignerPayload.ts`
```
- const data = createType('ExtrinsicPayload', payload, { version: payload.version }).toHex();
+ const data = u8aToHex(createType('ExtrinsicPayload', payload, { version: payload.version }).toU8a(true));
```

### CODE REVIEW

**Comment by jacogr** [comment]
Actually the same as the little comment PR I put in last night. 100% correct. (Need to bump the actual tests on this, this can be properly checked against ed25519 known - and would have avoided wasted time)

File: packages/types/src/primitive/Extrinsic/SignerPayload.ts [hunk 1]
```diff
@@ -63,7 +64,7 @@ export default class SignerPayload extends _Payload implements ISignerPayload {
    */
   public toRaw (): SignerPayloadRaw {
     const payload = this.toPayload();
-    const data = createType('ExtrinsicPayload', payload, { version: payload.version }).toHex();
+    const data = u8aToHex(createType('ExtrinsicPayload', payload, { version: payload.version }).toU8a(true));
```
Comment (jacogr) [inline packages/types/src/primitive/Extrinsic/SignerPayload.ts]:
```suggestion
    // NOTE Explicitly pass the bare flag to the method is encoded un-prefixed (non-decodable, for signing only)
    const data = u8aToHex(createType('ExtrinsicPayload', payload, { version: payload.version }).toU8a(true));
```
